server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres:postgres://pliutdfemafhjf:eccba6b733166e4f7b556d28bebba3684fbe856cc7e975517a9caca313b60dac@ec2-3-233-43-103.compute-1.amazonaws.com:5432/detsls6g1706ud
    username: pliutdfemafhjf
    password: eccba6b733166e4f7b556d28bebba3684fbe856cc7e975517a9caca313b60dac
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend
